spring:
  datasource:
  cache:
    type: redis
    redis:
      time-to-live: 60m
  data:
    redis:
      host: r-2ze2rcsue2g85lmeippd.redis.rds.aliyuncs.com
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      username: fraut_detection
      # 密码
      password: sxsc@20250606
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
# 日志配置
logging:
  level:
    com.bank: debug
    org.springframework: warn
    com:
      zaxxer:
        hikari: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG

# Kafka配置
aliyun:
  kafka:
    ssl:
      truststore:
        location: ${SSL_LOCATION:classpath:truststore.jks}
        password: ${TRUSTSTORE_PWD:KafkaOnsClient}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:alikafka-serverless-cn-zp54ajv8a02-1000-vpc.alikafka.aliyuncs.com:9095,alikafka-serverless-cn-zp54ajv8a02-2000-vpc.alikafka.aliyuncs.com:9095,alikafka-serverless-cn-zp54ajv8a02-3000-vpc.alikafka.aliyuncs.com:9095}
    username: ${KAFKA_USERNAME:alikafka_serverless-cn-zp54ajv8a02}
    password: ${KAFKA_PASSWORD:s1HVAy3UMxBzBOO3Hng3pZnmxHikTqcY}
    security-protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
    sasl-mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
    topic: ${KAFKA_TOPIC:fraud-detection}
    consumer-group: ${KAFKA_CONSUMER_GROUP:fraud-detection-group}

  sls:
    endpoint: cn-beijing.log.aliyuncs.com  # SLS 服务地域Endpoint
    accessKeyId: LTAI5tEtdKgTHYTzB5FzenQQ          # 阿里云访问密钥ID
    accessKeySecret: l2IEYfJRIIte8IC9hv06ylFeuu17Xm  # 阿里云访问密钥Secret
    project: fraud-detection-log                # SLS 项目名称

# actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  server:
    port: 80